version: '3.4'

services:
  paulrbergsoliditytemplate:
    image: paulrbergsoliditytemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
